In [1]:
import argparse
import sys
from predict import run_predict

H:\anaconda3\envs\pytorch_cuda\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# for a give sequence and position, add "@" after if the position is "S" or "T"
def add_at_after_st(seq, position, unique_position):
    try:
        if seq[position-1] in ['S', 'T']:
            return seq[:position] + "@" + seq[position:]
    except:
        filename = "error_unique_position.txt"
        with open(filename, "a") as fasta_file:
            fasta_file.write(f"{unique_position}\n")            
    else:
        filename = "error_unique_position.txt"
        with open(filename, "a") as fasta_file:
            fasta_file.write(f"{unique_position}\n")

In [3]:
# donwload sequence object based on uniprot id from entrez and return the sequence as a str
def download_uniprot_seq(uniprot_id):
    Entrez.email = "luvul@med.umich.edu"  # Replace with your email
    handle = Entrez.efetch(db="protein", id=uniprot_id, rettype="fasta", retmode="text")
    sequence_record = SeqIO.read(handle, "fasta")
    # protein_1433_dic[uniprot_id] = sequence_record
    handle.close()
    sequence = str(sequence_record.seq)
    return sequence

In [4]:
model_loc = "H:\PhosphoLingo_ST_new.ckpt"
dataset_fasta = "test.fasta"
output_file = "test.csv"

In [ ]:
run_predict(model_loc, dataset_fasta, output_file)

In [32]:
import pandas as pd

In [33]:
augmented_original_Lingo_score_df = pd.read_csv("augmented_original_Lingo_score_df.csv")

In [34]:
augmented_original_Lingo_score_df

,Unnamed: 0,level_0,Hit site,Hit accession,Hit sequence,label,augmented data?,index,position,unique_position,phosphoLingo_score
0,0,0,S467p,P43681,LAKARSLsVQHMSSP,1,0,NaN,467,P43681_467,0.874
1,1,1,S779p,P11362,PLDQYSPsFPDTRSS,1,0,NaN,779,P11362_779,0.269
2,2,2,T32p,P98177,QSRPRSCtWPLPRPE,1,0,NaN,32,P98177_32,0.827
3,3,3,S8p,P14136,MERRRITsAARRSYV,1,0,NaN,8,P14136_8,0.784
4,4,4,S640p,P08151,AGVTRRAsDPAQAAD,1,0,NaN,640,P08151_640,0.961
...,...,...,...,...,...,...,...,...,...,...,...
1549,1549,551,T100p,M3XT83,ARSPPRPtLAREDDD,0,1,984.0,100,M3XT83_100,NaN
1550,1550,552,S860p,M3XMD3,EEGAASGsNGNFPEG,0,1,985.0,860,M3XMD3_860,NaN
1551,1551,553,S14p,M3YH13,NTINRSSsFGNFDRF,1,1,986.0,14,M3YH13_14,NaN
1552,1552,554,S12p,M3YUM4,PSDHLLDsLEELGDN,0,1,987.0,12,M3YUM4_12,NaN
1553,1553,555,S857p,M3Z3N2,RFRPRSNsTEREPQA,1,1,988.0,857,M3Z3N2_857,NaN

In [35]:
# get all the row which phosphoLingo_score is Nan
filtered_df = augmented_original_Lingo_score_df[augmented_original_Lingo_score_df['phosphoLingo_score'].isna()]

In [41]:
filtered_df.to_csv("no_phospholingo_score.csv")

In [42]:
filtered_df

,Unnamed: 0,level_0,Hit site,Hit accession,Hit sequence,label,augmented data?,index,position,unique_position,phosphoLingo_score
33,33,33,S68p,Q8IYK8,GAPRRRGsMPVPYKH,1,0,NaN,68,Q8IYK8_68,NaN
34,34,34,S333p,Q8IYK8,FFKQRSRsCHDLSVL,1,0,NaN,333,Q8IYK8_333,NaN
54,54,54,S230p,P17035,KKLTRRAsFSAQSAS,1,0,NaN,230,P17035_230,NaN
66,66,66,S51p,Q48BD8,PVLERSKsAPALLTA,1,0,NaN,51,Q48BD8_51,NaN
67,67,67,S51p,Q48BD8,PVLERAKsAPALLTA,1,0,NaN,51,Q48BD8_51,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1549,1549,551,T100p,M3XT83,ARSPPRPtLAREDDD,0,1,984.0,100,M3XT83_100,NaN
1550,1550,552,S860p,M3XMD3,EEGAASGsNGNFPEG,0,1,985.0,860,M3XMD3_860,NaN
1551,1551,553,S14p,M3YH13,NTINRSSsFGNFDRF,1,1,986.0,14,M3YH13_14,NaN
1552,1552,554,S12p,M3YUM4,PSDHLLDsLEELGDN,0,1,987.0,12,M3YUM4_12,NaN
1553,1553,555,S857p,M3Z3N2,RFRPRSNsTEREPQA,1,1,988.0,857,M3Z3N2_857,NaN

In [39]:
uniprot_dict = {}

In [ ]:
from Bio import SeqIO
from Bio import Entrez
filename = "no_phospholingo_score.fasta"
for index, row in filtered_df.iterrows():
    uniprot_id = row["Hit accession"].split("-")[0]
    position = row["position"]
    unique_position = row["unique_position"]
    if uniprot_id in uniprot_dict:
        seq = uniprot_dict[uniprot_id]
    else:
        try:
            seq = download_uniprot_seq(uniprot_id)
            uniprot_dict[uniprot_id] = seq
        except:
            continue
    print(unique_position, len(seq))
    mut_seq = add_at_after_st(seq, position, unique_position)
    with open(filename, "a") as fasta_file:
        fasta_file.write(f">{unique_position}\n")
        fasta_file.write(f"{mut_seq}\n")

Q8IYK8_68 340
Q8IYK8_333 340
P17035_230 718
Q48BD8_51 447
Q48BD8_51 447
Q9V491_1794 1945
Q45VV3_168 395
Q29495_31 207
Q29495_205 207
Q9R1V6_855 904
Q9R1V6_832 904
P56402_256 271
P56402_269 271
Q60875_885 985
O55043_516 646
O55043_526 646
P06685_23 1023
Q61337_136 204
Q9QUN3_152 457
Q04982_769 766
Q04982_365 766
O88778_2845 3938
Q02294_2126 2336
P97756_74 505
Q8BGU5_100 341
Q923J1_1403 1863
O08785_845 855
Q07174_400 467
Q07174_443 467
P26955_603 896
Q9Z2F5_147 430
Q8VDF3_369 370
Q8VDF3_369 370
Q8VDF3_369 370
Q8VDF3_369 370
Q6S7F2_411 904
Q58FA4_395 860
Q9WVS8_486 806
Q6P4D5_29 195
Q8BGI4_322 693
Q86V87_325 743
Q9WVH4_32 672
Q9WVH3_197 505
Q9WVH3_32 505
O89100_254 322
P03995_8 430
P08050_373 382
P42260_846 908
P42260_868 908
Q60760_455 621
P97879_956 1112
P18266_9 420
P68431_10 136
P68431_10 136
P68431_28 136
O88704_867 910
O88704_810 910
Q8C2B3_178 938
Q8C2B3_479 938
Q8C2B3_344 938
P35569_637 1233
P81122_573 1321
Q9QWL7_44 433
Q9QWL7_9 433
Q6VV64_264 394
O88448_575 599
Q61097_297 873
Q61097_392 873
Q3UVC0_475 951
Q3UVC0_314 951
Q5S006_910 2527
Q5S006_935 2527
Q5D1E7_513 596
Q5D1E7_494 596
O35618_341 489
Q61083_283 619
P05432_250 459
P05432_250 459
Q08874-8_173 526
Q9DBR7_909 1029
Q9ERR1_251 345
Q9ERR1_336 345
Q8CFI0_396 1004
Q00961_1083 1237
Q2LC84_275 652
Q2LC84_294 652
A1L1I3_305 614
P22829_350 597
B2RWS6_89 2412
Q63531_154 735
Q7Z309_25 247
Q7Z309_50 247
Q9Z340_852 1337
Q9Z340_889 1337
Q63085_279 1108
Q63085_302 1108
P20942_73 246
P20942_54 246
Q9UBF8-2_294 816
P97474_90 317
P09217_186 592
Q66T02_938 1073
Q66T02_92 1073
Q8BJ56_406 486
Q9JJ26_205 767
Q9JJ26_241 767
Q8CFH6_587 931
Q6P4S6_551 1369
Q9NS23-2_175 344
Q9NS23-2_178 344
Q9NS23-2_179 344
O75628_18 298
Q8VEL9_334 341
O08773_218 544
Q9NS28_218 235
Q9NS28_218 235
Q9NS28_49 235
Q80WQ6_83 827
Q9JIR4_241 1615
Q9JIR4_287 1615
Q99NE5-7_413 1463
Q8CBD1_1003 1161
Q8CBD1_102 1161
O88667_301 308
O88667_301 308
Q9R1U5_186 776
Q60670_577 779
Q60787_376 533
P16546_1302 2472
P51557_194 284
Q9EPK5_89 395
P04177_19 498
Q60610_60 1591
Q3U182_171 692
Q3U182_275 692
Q3U182_369 692
P49816-2_1211 1809
P22893_52 319
P22893_178 319
Q05086-2_485 875
O70405_555 1051
Q80U87_680 1080
Q80U87_680 1080
P46938_112 488
Q0VGT2_956 1544
P10637_506 733
Q91ZP3_285 924
Q91ZP3_287 924
P81122_1137 1321
Q6I9V6_140 198
P46937-2_109 504
Q8IVT5_291 923
Q8IVT5_268 923
Q9JIR4_379 1615
Q9Y2K2_916 1321
Q9Y2K2_163 1321
Q12802-2_1582 2813
Q12802-2_1584 2813
P12023-2_668 770
O55043_560 646
P06685_16 1023
Q61337_155 204
Q61337_128 204
Q9QUN3_144 457
Q9YGC1_170 552
Q8VDF3_367 370
Q8VDF3_368 370
Q8VDF3_370 370
Q9R0Z9_420 1092
Q9DB52_119 284
G3V7R4_206 649
P55041_286 295
P03995_12 430
P03995_15 430
P08050_244 382
Q60760_78 621
P81122_303 1321
P81122_401 1321
P81122_517 1321
P81122_556 1321
Q9UQB8-5_511 552
Q6VV64_276 394
Q61097_838 873
Q5D1E7_21 596
Q5D1E7_61 596
Q5D1E7_62 596
Q5D1E7_362 596
Q5D1E7_439 596
Q5D1E7_470 596
P05432_248 459
Q9ERR1_198 345
Q9ERR1_219 345
Q9ERR1_231 345
Q63531_363 735
Q63531_380 735
Q63531_732 735
Q61409_421 1100
O35618_402 489
P20942_6 246
P20942_36 246
P20942_106 246
Q66T02_806 1073
Q66T02_936 1073
Q9JJ26_188 767
Q9JJ26_432 767
O35929_290 297
O88667_299 308
Q9R210_461 475
P24529_40 498
Q60787_410 533
Q60787_207 533
Q61037_1421 1814
Q61037_1805 1814
P49816-2_1087 1809
P49816-2_1089 1809
P49816-2_1423 1809
O70405_659 1051
Q61037_1340 1814
Q80U87_678 1080
Q8IYK8_54 340
P47709_234 684
P10637_504 733
P22893_249 319
P22893_189 319
Q8CFH6_484 931
Q45VV3_88 395
Q45VV3_227 395
Q9Z2F5_147 430
Q61083_283 619
Q8VEL9_334 341
Q9NS28_218 235
O88667_301 308
Q80U87_680 1080
Q0VGT2_956 1544
P22893_178 319
Q2QLE5_660 1480
Q5RA72_13 432
Q5RA72_7 432
Q5R598_152 257
Q5R6Z1_46 470
Q2IBE4_768 1480
Q5R4T3_34 268
Q2IBE4_737 1480
Q6XLJ0_226 777
Q6XLJ0_6 777
Q6XLJ0_234 777
Q6XLJ0_267 777
Q6XLJ0_211 777
Q6XLJ0_203 777
Q8MJK1_20 127
A7E3S4_269 648
Q08E26_127 693
Q3T904_761 839
Q28918_57 285
Q2KIC2_94 477
Q3ZCI8_152 257
Q28918_56 285
Q28918_195 285
Q5EAD0_326 521
Q29RP3_18 298
A7E3S4_233 648
Q17QE6_14 167
O97790_593 1165
Q08DH4_508 622
O77560_73 245
O77560_54 245
O77560_36 245
Q9XS39_54 245
Q9XS39_36 245
P56951_373 491
P56951_365 491
P41686_54 245
O19001_157 198

In [ ]:
with open("uniprot.txt", "a") as fasta_file:
    fasta_file.write(uniprot_dict)